In [1]:
""" pd-test-df.py """
import pandas as pd

a = pd.DataFrame([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(a)

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90


In [2]:
""" pd-test-s.py """
import pandas as pd, numpy as np

s = pd.Series([1.0, 3.0, 5.0, 7.0, 9.0])

print(s)

0    1.0
1    3.0
2    5.0
3    7.0
4    9.0
dtype: float64


In [3]:
""" pd-test-key.py """
import pandas as pd

# 키, 몸무게, 유형 데이터프레임 생성하기
tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2 ],
    "height": [ 170,  180,  155,  143,  154  ],
    "type":   [ "f", "n", "n", "t", "t"]
})

# 몸무게 목록 추출하기
print("몸무게 목록")
print(tbl["weight"])

# 몸무게와 키 목록 추출하기
print("몸무게와 키 목록")
print(tbl[["weight","height"]])

몸무게 목록
0    80.0
1    70.4
2    65.5
3    45.9
4    51.2
Name: weight, dtype: float64
몸무게와 키 목록
   weight  height
0    80.0     170
1    70.4     180
2    65.5     155
3    45.9     143
4    51.2     154


In [4]:
""" pd-test-slice.py """
import pandas as pd

# 키, 몸무게, 유형 데이터프레임 생성하기
tbl = pd.DataFrame({
"weight": [ 80.0, 70.4, 65.5, 45.9, 51.2, 72.5 ],
"height": [ 170, 180, 155, 143, 154, 160 ],
"type": [ "f", "n", "n", "t", "t", "f" ]
})

# (0부터 세었을 때) 2~3번째 데이터 출력
print("tbl[2:4]\n", tbl[2:4])

# (0부터 세었을 때) 3번째 이후의 데이터 출력하기
print("tbl[3:]\n",tbl[3:])

tbl[2:4]
    weight  height type
2    65.5     155    n
3    45.9     143    t
tbl[3:]
    weight  height type
3    45.9     143    t
4    51.2     154    t
5    72.5     160    f


In [5]:
""" pd-test-filter.py """
import pandas as pd

# 키, 몸무게, 유형 데이터프레임 생성하기
tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2, 72.5 ],
    "height": [ 170,  180,  155,  143,  154,  160  ],
    "gender": [ "f",  "m",  "m",  "f",  "f",  "m"  ]
})

print("--- height가 160 이상인 것")
print(tbl[tbl.height >= 160])

print("--- gender가 m 인 것")
print(tbl[tbl.gender == "m"])

--- height가 160 이상인 것
   weight  height gender
0    80.0     170      f
1    70.4     180      m
5    72.5     160      m
--- gender가 m 인 것
   weight  height gender
1    70.4     180      m
2    65.5     155      m
5    72.5     160      m


In [6]:
""" pd-test-sort.py """
import pandas as pd

# 키, 몸무게, 유형 데이터프레임 생성하기
tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2, 72.5 ],
    "height": [ 170,  180,  155,  143,  154,  160  ],
    "gender": [ "f",  "m",  "m",  "f",  "f",  "m"  ]
})

print("--- 키로 정렬")
print(tbl.sort_values(by="height"))

print("--- 몸무게로 정렬")
print(tbl.sort_values(by="weight", ascending=False))

--- 키로 정렬
   weight  height gender
3    45.9     143      f
4    51.2     154      f
2    65.5     155      m
5    72.5     160      m
0    80.0     170      f
1    70.4     180      m
--- 몸무게로 정렬
   weight  height gender
0    80.0     170      f
5    72.5     160      m
1    70.4     180      m
2    65.5     155      m
4    51.2     154      f
3    45.9     143      f


In [7]:
""" pd-test-rot.py """
import pandas as pd

tbl = pd.DataFrame([
    ["A", "B", "C"],
    ["D", "E", "F"],
    ["G", "H", "I"]
])

print(tbl)
print("---")
print(tbl.T)

   0  1  2
0  A  B  C
1  D  E  F
2  G  H  I
---
   0  1  2
0  A  D  G
1  B  E  H
2  C  F  I


In [8]:
""" pd-test-calc.py """
import numpy as np

# 10개의 float32 자료형 데이터 생성
v = np.zeros(10, dtype=np.float32)
print(v)

# 연속된 10개의 uint64 자료형 데이터 생성
v = np.arange(10, dtype=np.uint64)
print(v)

# v 값을 3배하기
v *= 3
print(v)

# v의 평균 구하기
print(v.mean())

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 1 2 3 4 5 6 7 8 9]
[ 0  3  6  9 12 15 18 21 24 27]
13.5


In [9]:
""" pd-test-norm.py """
import pandas as pd

# 키, 체중, 유형 데이터프레임 생성하기
tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2, 72.5 ],
    "height": [ 170,  180,  155,  143,  154,  160  ],
    "gender": [ "f",  "m",  "m",  "f",  "f",  "m"  ]
})

# 키와 몸무게 정규화하기
tbl["weight"] /= 100
tbl["height"] /= 200
print(tbl)

   weight  height gender
0   0.800   0.850      f
1   0.704   0.900      m
2   0.655   0.775      m
3   0.459   0.715      f
4   0.512   0.770      f
5   0.725   0.800      m


In [10]:
""" pd-test-norm2.py """
import pandas as pd

# 키, 체중, 유형 데이터프레임 생성하기
tbl = pd.DataFrame({
    "weight": [ 80.0, 70.4, 65.5, 45.9, 51.2, 72.5 ],
    "height": [ 170,  180,  155,  143,  154,  160  ],
    "gender": [ "f",  "m",  "m",  "f",  "f",  "m"  ]
})

# 키와 몸무게 정규화하기
# 최댓값과 최솟값 구하기
def norm(tbl, key):
    c = tbl[key]
    v_max = c.max()
    v_min = c.min()
    print(key, "=", v_min, "-", v_max)
    tbl[key] = (c - v_min) / (v_max - v_min)

norm(tbl, "weight")
norm(tbl, "height")
print(tbl)

weight = 45.9 - 80.0
height = 143 - 180
     weight    height gender
0  1.000000  0.729730      f
1  0.718475  1.000000      m
2  0.574780  0.324324      m
3  0.000000  0.000000      f
4  0.155425  0.297297      f
5  0.780059  0.459459      m


In [11]:
# Chang Pandas DataFrame to NumPy ndarray
n = tbl.values
print(n)

[[1.0 0.7297297297297297 'f']
 [0.7184750733137831 1.0 'm']
 [0.5747800586510264 0.32432432432432434 'm']
 [0.0 0.0 'f']
 [0.15542521994134909 0.2972972972972973 'f']
 [0.7800586510263929 0.4594594594594595 'm']]
