In [8]:
import numpy as np

a = np.arange(15).reshape(3, 5)

print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>


In [10]:
a = a.reshape(5,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [18]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.zeros((3,4))
print(b)
c = np.ones((2,3,4), dtype=np.int64)
print(c)
d = np.empty((2,3))
print(d)
e = np.arange(10, 100, 10)
print(e)

[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]
[10 20 30 40 50 60 70 80 90]


In [20]:
A = np.array( [20,30,40,50] )
B = np.arange(4)
# B = [0,1,2,3]

C = A-B
print(C)

D = B**2
print(D)

print(A<35)

[20 29 38 47]
[0 1 4 9]
[ True  True False False]


In [23]:
""" The Comparison between List and Numpy """
import time
import numpy as np

_LARGE_NUMBER = 100000000

a = range(_LARGE_NUMBER)
b = range(_LARGE_NUMBER)
c = []

start = time.time()
for i in range(_LARGE_NUMBER):
    c.append(a[i]*b[i])
end = time.time()
print('elasped time =', end-start)

a = np.arange(_LARGE_NUMBER)
b = np.arange(_LARGE_NUMBER)

start = time.time()
c = a*b
end = time.time()
print('elasped time =', end-start)

elasped time = 22.311246395111084
elasped time = 0.9195413589477539


In [24]:
""" The Comparison between List and Numpy """
import time
import numpy as np

_LARGE_NUMBER = 10000000

a = range(_LARGE_NUMBER)
b = range(_LARGE_NUMBER)
c = []

start = time.time()
for i in range(_LARGE_NUMBER):
    c.append(a[i]*b[i])
end = time.time()
print('elasped time =', end-start)

a = np.arange(_LARGE_NUMBER)
b = np.arange(_LARGE_NUMBER)

start = time.time()
c = a*b
end = time.time()
print('elasped time =', end-start)

elasped time = 2.2412140369415283
elasped time = 0.0939939022064209


In [26]:
A = np.array( [[1,1],
             [0,1]] )
B = np.array( [[2,0],
              [3,4]] )

C = A*B    # elementwise product
D = A@B    # matrix product
print(C)
print(D)

X = [1,2,3,4]
Y = [1,0,1,0]

F = np.inner(X,Y)    # inner product
print(F)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
4


In [ ]:
import pandas as pd

xl_file = 'abc.xlsx'
df = pd.read_excel(xl_file)
print(df)